FEAT:
Felipe-devv/java_advanced_project pull request #8
Opened 2024-11-09 12:59 UTC by Felipe-devv

- config jdbc
- CRUD for paragon
- jdbc pom, properties, repo, service, controller

2024-11-09 13:12 UTC, Felipe-devv commented
ENDPOINTY TAKIE, bez 1 ewentualnie http://localhost:8080/paragones/1
BODY
{
  "id":2,
  "miasto": "Warszawa",
  "kodPocztowy": "16-124",
  "kebab": 1,
  "turek": 1,
  "suma": 29
}

2024-11-09 17:21 UTC, Sprysio requested changes
albo to u mnie po prostu nie dziala albo to po chuju zrobione:
![Screenshot from 2024-11-09 18-10-46](https://github.com/user-attachments/assets/3b89f68a-ac30-486d-87c3-71870b3b70fe)

![Screenshot from 2024-11-09 18-13-46](https://github.com/user-attachments/assets/cd9fb6e0-82c7-4271-bf49-6a57bc922b5a)

ale ten update to na pewno nie zadziala to jestem pewny


![Screenshot from 2024-11-09 18-16-02](https://github.com/user-attachments/assets/f5ecbda7-13a1-41f8-afdb-032436815222)

2024-11-09 17:24 UTC, Sprysio commented
@spixxer  @Felipe-devv znaczy nie ze nie zadziala tylko chujowo zrobiony tam wiesz trzeba wybrac paragon do aktualizacji np. paragone/{idParagone} a nie ze bedzie id w dto chyba ze czegos nie wiem

2024-11-10 09:29 UTC, Felipe-devv commented
Mi działało, nawet bez slesza
I poprawiłem GETY
I id musi zostać w body, nie ma innej możliwości
![image](https://github.com/user-attachments/assets/dc20c101-28d9-4fdc-8f55-4ae00eeac4bc)
![image](https://github.com/user-attachments/assets/dcab1b88-38e1-4a99-bc22-c66ba0ae86c5)
![image](https://github.com/user-attachments/assets/34977869-273f-4035-864a-bf45ddbaa906)
![image](https://github.com/user-attachments/assets/e44385bb-f7d6-47ec-8fde-a65e272b2626)
![image](https://github.com/user-attachments/assets/b91911b3-b53b-45bc-ad39-6a1ce2a76e5b)

2024-11-10 09:34 UTC, Felipe-devv commented
@Sprysio jak ci teraz nie zadziała, bo już się upewniłem, że wszystko działa, tylko oczywiście bez jakiejkolwiek walidacji czy obsługi wyjątków, więc musi być dobrze dodane :), to znaczy, że coś z jakąś konfiguracją albo czymś masz inaczej niż ja

2024-11-10 11:13 UTC, Sprysio commented
Dziala teraz ale troche po chuju zrobione nie bede ukrywal

2024-11-10 11:14 UTC, Sprysio approved these changes
tera dziala

2024-11-10 11:14 UTC, merged